<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="5" failures="1">
  <testsuite name="Root Suite" timestamp="2023-03-07T08:16:09" tests="0" file="cypress/e2e/keywords.cy.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Keywords" timestamp="2023-03-07T08:16:09" tests="5" time="0.0000" failures="1">
    <testcase name="Keywords &quot;before all&quot; hook for &quot;When keyword has language, it must be danish&quot;" time="0.0000" classname="&quot;before all&quot; hook for &quot;When keyword has language, it must be danish&quot;">
      <failure message="The following error originated from your application code, not from Cypress.

  &gt; Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
    ╷
114 │       @each $key, $value in $gutters {
    │                             ^^^^^^^^
    ╵
  node_modules/bootstrap/scss/mixins/_grid.scss 114:29       @content
  node_modules/bootstrap/scss/mixins/_breakpoints.scss 68:5  media-breakpoint-up()
  node_modules/bootstrap/scss/mixins/_grid.scss 72:5         make-grid-columns()
  node_modules/bootstrap/scss/_grid.scss 32:3                @import
  src/scss/custom-bootstrap.scss 20:9                        root stylesheet

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Keywords`

Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail" type="Error"><![CDATA[Error: The following error originated from your application code, not from Cypress.

  > Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
    ╷
114 │       @each $key, $value in $gutters {
    │                             ^^^^^^^^
    ╵
  node_modules/bootstrap/scss/mixins/_grid.scss 114:29       @content
  node_modules/bootstrap/scss/mixins/_breakpoints.scss 68:5  media-breakpoint-up()
  node_modules/bootstrap/scss/mixins/_grid.scss 72:5         make-grid-columns()
  node_modules/bootstrap/scss/_grid.scss 32:3                @import
  src/scss/custom-bootstrap.scss 20:9                        root stylesheet

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Keywords`

Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail
    at Object../node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/scss/custom-bootstrap.scss (http://localhost:4000/main.iframe.bundle.js:460:7)
    at __webpack_require__ (http://localhost:4000/runtime~main.iframe.bundle.js:854:30)
    at fn (http://localhost:4000/runtime~main.iframe.bundle.js:151:20)
    at Object../src/scss/custom-bootstrap.scss (http://localhost:4000/main.iframe.bundle.js:82215:27)
    at __webpack_require__ (http://localhost:4000/runtime~main.iframe.bundle.js:854:30)
    at fn (http://localhost:4000/runtime~main.iframe.bundle.js:151:20)
    at Module../.storybook/preview.js (http://localhost:4000/main.iframe.bundle.js:25:89)
    at __webpack_require__ (http://localhost:4000/runtime~main.iframe.bundle.js:854:30)
    at fn (http://localhost:4000/runtime~main.iframe.bundle.js:151:20)
    at Module../.storybook/preview.js-generated-config-entry.js (http://localhost:4000/main.iframe.bundle.js:309:124)]]></failure>
    </testcase>
  </testsuite>
</testsuites>